### ISSUE TITLE
Exception on "Revert Order"

### ISSUE THREAD

**Issue by vladox** [brain-tec/swisspost-odoo-yellowcube#41]
We are getting this exception when we try to revert an order:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, args, *kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, args, *kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 810, in call
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/odoo/local/pc_connect_warehouse_yellowcube/stock_return_picking_ext.py", line 237, in create_returns
    return super(stock_return_picking_ext, self).create_returns(cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, args, *kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/wizard/stock_return_picking.py", line 178, in create_returns
    new_picking_id, pick_type_id = self._create_returns(cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/odoo/local/pc_connect_warehouse_yellowcube/stock_return_picking_ext.py", line 38, in _create_returns
    return super(stock_return_picking_ext, self)._create_returns(self, cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, args, *kwargs)
TypeError: _create_returns() got multiple values for keyword argument 'context'

**Comment by ghost** [comment]
Newbie error. Adding self to the parameters. I'll solved it in a sec.

File "/opt/odoo/local/pc_connect_warehouse_yellowcube/stock_return_picking_ext.py", line 38, in _create_returns
return super(stock_return_picking_ext, self)._create_returns(self, cr, uid, ids, context=context)
